OWNER_NAME="𝐉𝚯𝐘𝚩𝚯𝐘"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "𝙈𝙄𝙍𝘼𝙂𝙀-𝙈𝘿 𝙑1"
IMAGE_MENU= "https://telegra.ph/file/e8b25ea0f33c577e9da53.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛𝐉𝚯𝐘𝚩𝚯𝐘᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'
